chunks: 16
env_id: Env_ros
extra: rw_e = -6.0 *e^2, reward for last position 10*e^2, reward for first action
f_robot: 100
fl_noILC: false
info: multi task
kp: 0.4
kv: 0.25
ldde: 0.0
lde: 0.04
le: 0.02
n_envs: 64
n_ep_reset: 5
n_update: 200
pi:
- 64
- 64
scaling: 2
seed: 42
stayT: 0.0
taskT: 1.0
vf:
- 64
- 64
