# Parametri di configurazione per l'ambiente gym

default : &default
  env_id    : '' # environment name

  taskT     : 3.0   # [s]
  fs        : 500   # Frequenza di campionamento
  reset_epN : 10    # max consecutive episodes

  batch     : 64    # mini-batch size
  n_envs    : 5     # number of environment
  updateN   : 200   # number of policy updates

  noise_q   : 0.0

  weight_s  : 0.0
  weight_t  : 0.0
  std_s     : 0.0

coupled : &coupled
  <<: *default
  env_id    : 'EnvRLILC-v0' # environment name
  fs        : 50   # Frequenza di campionamento
  n_envs    : 5     # number of environment
  updateN   : 200   # number of policy updates
  weight_s  : 0.0
  weight_t  : 0.0
  std_s     : 0.0

decoupled : &decoupled
  <<: *default
  env_id    : 'EnvRLILC_DEC-v0' # environment name
  weight_s  : 0.0
  weight_t  : 0.0
  std_s     : 0.0

coupled_rew1 : &coupled_rew1
  <<: *default
  env_id    : 'EnvRLILC_rew1-v0' # environment name
  n_envs    : 2     # number of environment
  weight_s  : 0.1
  weight_t  : 0.0
  std_s     : 0.01

coupled2 : &coupled2
  <<: *default
  env_id    : 'EnvRLILC-v1' # environment name
  n_envs    : 5     # number of environment
  updateN   : 200   # number of policy updates
