task:
  env:
    numActions: 2
    numObservations: 7
    clipObservations: 100.0
    episodeLength: 2.0
    heightDes: 1.0
    control:
      actionScale: 3.141592653589793
    learn:
      qScale: 3.141592653589793
      qDotScale: 80.0
  sim:
    dt: 0.005
train:
  params:
    network:
      name: actor_critic
      separate: false
      space:
        continuous:
          mu_activation: None
          sigma_activation: None
          mu_init:
            name: default
          sigma_init:
            name: const_initializer
            val: 0
          fixed_sigma: true
      mlp:
        units:
        - 256
        - 128
        - 64
        activation: elu
        d2rl: false
        initializer:
          name: default
        regularizer:
          name: None
    config:
      normalize_input: true
      normalize_value: true
