task:
  name: SoftlegJumpCinque
  physics_engine: ${..physics_engine}
  env:
    numEnvs: ${resolve_default:128,${...num_envs}}
    envSpacing: 3.0
    resetDist: 3.0
    maxEffort: 20.0
    numActions: 2
    numObservations: 7
    clipObservations: 100.0
    clipActions: 15.0
    controlFrequencyInv: 4
    episodeLength: 2.0
    heightDes: 1.0
    lengthSoftLeg: 0.45
    whenToPrint: 5
    terrain:
      staticFriction: 1.0
      dynamicFriction: 1.0
      restitution: 0.0
    defaultJointAngles:
      softleg_1_cart_joint: 0.11
      softleg_1_hip_joint: -0.75
      softleg_1_knee_joint: -0.75
    initState:
      q:
      - 0.11
      - -0.75
      - -0.75
      qDot:
      - 0.0
      - 0.0
      - 0.0
    control:
      stiffness:
      - 0.8674531575294934
      - 0.8674531575294935
      damping:
      - 0.08674531575294935
      - 0.08674531575294935
      decimation: 1
      actionScale: 3.141592653589793
    learn:
      qScale: 3.141592653589793
      qDotScale: 80.0
      actionScale: 3.141592653589793
      addNoise: true
      noiseLevel: 0.1
      qNoise: 0.01
      qDotNoise: 0.01
      wControlVarSat: 1
      wControlVar: 1
      wErrDistance: 1
      wConfigStartEnd: 1
      wVelFinal: 1
      wHeightGneral: 1
      wFootDownPrismatic: 1
      wHipMinusAllTime: 1
      wGroundForce: 1
      wActionRate: 1
      wJointAcc: 1
      torqueRewardScale: 1
      jointAccRewardScale: 1
      actionRateRewardScale: 1
      terminationRewardScale: 1
      velocityRewardScale: 1
      timeRewardScale: 1
      storageheightRewardScale: 1
      ground_forcesRewardScale: 1
      distanceScale: 1
      finalConfig: 1
      footDownPrismatic: 1
      hipMinusAllTheTime: 1
  sim:
    dt: 0.005
    preTime: 8.0
    use_gpu_pipeline: ${eq:${...pipeline},"gpu"}
    gravity:
    - 0.0
    - 0.0
    - -9.81
    add_ground_plane: true
    add_distant_light: true
    use_flatcache: true
    enable_scene_query_support: false
    disable_contact_processing: true
    enable_cameras: false
    default_physics_material:
      static_friction: 1.0
      dynamic_friction: 1.0
      restitution: 0.0
    physx:
      worker_thread_count: ${....num_threads}
      solver_type: ${....solver_type}
      use_gpu: ${eq:${....sim_device},"gpu"}
      solver_position_iteration_count: 4
      solver_velocity_iteration_count: 1
      contact_offset: 0.01
      rest_offset: 0.0
      bounce_threshold_velocity: 0.2
      friction_offset_threshold: 0.04
      friction_correlation_distance: 0.025
      enable_sleeping: true
      enable_stabilization: true
      max_depenetration_velocity: 100.0
      gpu_max_rigid_contact_count: 524288
      gpu_max_rigid_patch_count: 163840
      gpu_found_lost_pairs_capacity: 4194304
      gpu_found_lost_aggregate_pairs_capacity: 35629056
      gpu_total_aggregate_pairs_capacity: 4194304
      gpu_max_soft_body_contacts: 1048576
      gpu_max_particle_contacts: 1048576
      gpu_heap_capacity: 134217728
      gpu_temp_buffer_capacity: 33554432
      gpu_max_num_partitions: 8
    Softleg:
      override_usd_defaults: false
      enable_self_collisions: false
      enable_gyroscopic_forces: false
      solver_position_iteration_count: 4
      solver_velocity_iteration_count: 1
      sleep_threshold: 0.005
      stabilization_threshold: 0.001
      density: -1
      max_depenetration_velocity: 100.0
      contact_offset: 0.02
      rest_offset: 0.0
train:
  params:
    seed: ${...seed}
    algo:
      name: a2c_continuous
    model:
      name: continuous_a2c_logstd
    network:
      name: actor_critic
      separate: false
      space:
        continuous:
          mu_activation: None
          sigma_activation: None
          mu_init:
            name: default
          sigma_init:
            name: const_initializer
            val: 0
          fixed_sigma: true
      mlp:
        units:
        - 256
        - 128
        - 64
        activation: elu
        d2rl: false
        initializer:
          name: default
        regularizer:
          name: None
    load_checkpoint: ${if:${...checkpoint},True,False}
    load_path: ${...checkpoint}
    config:
      name: ${resolve_default:JumpingSoftlegTre,${....experiment}}
      full_experiment_name: ${.name}
      device: ${....rl_device}
      device_name: ${....rl_device}
      env_name: rlgpu
      ppo: true
      mixed_precision: false
      normalize_input: true
      normalize_advantage: true
      normalize_value: true
      num_actors: ${....task.env.numEnvs}
      reward_shaper:
        scale_value: 0.1
      value_bootstrap: true
      gamma: 0.99
      tau: 0.95
      learning_rate: 0.0003
      lr_schedule: adaptive
      kl_threshold: 0.008
      score_to_win: 2000000000000000
      max_epochs: ${resolve_default:2000,${....max_iterations}}
      save_best_after: 50
      save_frequency: 50
      grad_norm: 1.0
      entropy_coef: 0.001
      truncate_grads: true
      e_clip: 0.2
      horizon_length: 512
      minibatch_size: 16384
      mini_epochs: 8
      critic_coef: 4
      clip_value: true
      seq_len: 4
      bounds_loss_coef: 0.001
      print_stats: true
task_name: ${task.name}
experiment: SoftlegJump040_target13
num_envs: 256
seed: 42
torch_deterministic: false
max_iterations: ''
physics_engine: physx
pipeline: gpu
sim_device: gpu
device_id: 0
rl_device: cuda:0
num_threads: 4
solver_type: 1
test: false
checkpoint: ''
headless: true
livestream: false
mt_timeout: 30
wandb_activate: false
wandb_group: ''
wandb_name: ${train.params.config.name}
wandb_entity: ''
wandb_project: omniisaacgymenvs
