# parameters of node
# NOTE: some nodes need robot urdf path and rl_model_path, set them on launch file

command_rlilc_node:
  
  ros__parameters:
    
    joint_names: ['LH_HFE', 'LH_KFE']
    
    topic:
      joint_state : '/joint_states'
      command     : '/joint_controller/command'
      feedback    : '/PD_joint_state'
      command_id  : '/command_id'
    
    task:
      duration    : 5.0   # NOTE consider to modify id_selector_node parameter
      wait_t      : 1.0
      post_wait_t : 1.0
      pf          : [-0.15, 0.15]
    
    rate: 
      command: 200.0
      policy: 50.0
    
    env:
      q_max   : [3.1415927, 3.1415927]
      dq_max  : [15.0, 15.0]
      ddq_max : [15.0, 15.0]
      u_max   : [0.05, 0.005]
    
    controller_gain:
      ilc:
        le: 0.0002
        lde: 0.0004
        ldde: 0.0008
  

homing_node:
  
  ros__parameters:
    
    joint_names: ['LH_HFE', 'LH_KFE']
    
    topic:
      joint_state : '/joint_states'
      command     : '/joint_controller/command'
      command_id  : '/command_id'
    
    task:
      duration    : 5.0     # NOTE consider to modify id_selector_node parameter
      wait_t      : 1.0
      post_wait_t : 1.0
      pf          : [0.0, 0.0]
    
    rate: 
      command: 200.0

id_selector_node:

  topic:
    command_id: '/command_id'
  
    task:
      duration_homing : 10.0 # NOTE consider to modify command_rlilc_node parameter
      duration_rlilc  : 10.0 # NOTE consider to modify homing_node parameter
  
  rate : 200.0