# # config.yaml

# trajectory_node:
  
#   ros__parameters:
    
#     joint_names : ['LH_HFE', 'LH_KFE']
    
#     topic :
#       joint_state    : '/joint_states'
#       high_rate_traj : '/high_rate_traj'
#       low_rate_traj  : '/low_rate_traj'
    
#     rate :
#       high_rate : 200.0
#       low_rate  : 50.0

#     task :
#       duration : 2.0
#       wait_t   : 5.0
#       pf       : [-0.25, 0.0]


# fake_pd_node:
  
#   ros__parameters:
    
#     joint_names: ['LH_HFE', 'LH_KFE']
    
#     topic:
#       joint_state : '/joint_states'
#       des_traj    : '/high_rate_traj'
#       command     : '/joint_controller/command'
    
#     rate: 200.0


command_rlilc_node:
  
  ros__parameters:
    
    joint_names: ['LH_HFE', 'LH_KFE']
    
    topic:
      joint_state : '/joint_states'
      command     : '/joint_controller/command'
      feedback    : 'PD_joint_state'
      command_fl  : 'command_bool'
    
    task:
      duration : 10.0
      wait_t   : 1.0
      post_wait_t : 1.0
      pf       : [-0.25, 0.15]
    
    rate: 
      command: 200.0
      policy: 50.0
    
    env:
      q_max   : [3.1415927, 3.1415927]
      dq_max  : [15.0, 15.0]
      ddq_max : [15.0, 15.0]
      u_max   : [0.05, 0.005]
    
    controller_gain:
      ilc:
        le: 0.0002
        lde: 0.0004
        ldde: 0.0008
  

homing_node:
  
  ros__parameters:
    
    joint_names: ['LH_HFE', 'LH_KFE']
    
    topic:
      joint_state : '/joint_states'
      command     : '/joint_controller/command'
    
    task:
      duration    : 10.0
      wait_t      : 1.0
      post_wait_t : 1.0
      pf          : [0.0, 0.0]
    
    rate: 
      command: 200.0
    